In [55]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

### Test pretrained transformer

In [3]:
tokenizer = AutoTokenizer.from_pretrained("distilgpt2") 
model = AutoModelForCausalLM.from_pretrained("distilgpt2", output_hidden_states=True)

In [41]:
text = "I am a very good"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=5, do_sample=False)

# Print the output
print('\n',tokenizer.decode(output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Input length of input_ids is 5, but `max_length` is set to 5. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.



 I am a very good person


In [25]:
# Print the token ides (of the input and output)
output

tensor([[1169, 1271,  530,  318, 3940,  416,  262, 1271,  734,   13,  198]])

### Tokenizer

In [61]:
# Print the input token ids
text = "water"
input = tokenizer(text, return_tensors="pt")['input_ids']
input

tensor([[7050]])

In [62]:
tokenizer.convert_ids_to_tokens(input[0])

['water']

### Embeddings

In [59]:
#Get the dictionary in form of embeddings. 50257 words represented by a vector of 768 dimensions
model.transformer.wte

Embedding(50257, 768)

In [63]:
# Get the embedding vector of token # 7050 ('water')
model.transformer.wte(torch.tensor(7050))

tensor([ 5.2998e-02, -1.7169e-01,  3.2423e-02,  2.5609e-01, -4.3002e-02,
        -4.1299e-02, -2.4445e-01, -3.7423e-01,  4.1352e-02,  5.9903e-02,
        -1.4376e-01,  3.7035e-02,  1.3621e-01,  1.6614e-01,  6.1061e-02,
        -3.1868e-02,  1.9956e-01, -4.2050e-02, -9.5827e-02,  5.1707e-02,
        -1.1667e-01,  1.0813e-01, -6.8580e-02,  8.0831e-03,  9.5967e-02,
        -7.2062e-02,  5.3088e-02,  1.9361e-02, -1.2315e-01, -1.4634e-01,
         6.5538e-02, -1.5686e-01,  3.9056e-01,  1.3620e-03, -8.9722e-03,
         1.3724e-01, -3.1975e-01, -9.8001e-02,  1.4857e-01, -2.5036e-01,
         9.1695e-02,  8.6520e-02, -1.4678e-01,  2.5058e-03, -7.7656e-02,
        -1.0479e-01, -1.1651e-01,  1.5521e-03,  1.1169e-01, -1.0569e-01,
         1.9711e-01,  1.8430e-01,  2.2550e-01, -3.0472e-02, -9.4010e-04,
        -2.0584e-01,  5.4215e-02,  4.0209e-02, -1.0987e-01,  1.0291e-01,
        -3.6758e-01,  1.2384e-01, -1.3192e-03,  6.5623e-02,  1.9731e-01,
         9.0394e-02, -1.1043e-01, -9.8674e-02,  1.1

### Source

- https://github.com/jalammar/jalammar.github.io/blob/master/notebooks/Simple_Transformer_Language_Model.ipynb